---
title: "missing_data_analysis"
format: html
---

```{r}
#| label: packages
#| message: FALSE

library(tidyverse)
library(readr)
library(here)
library(survey)
library(ggplot2)
library(survey)
library(extrafont)
library(naniar)
```

```{r}
#| label: data
#| message: FALSE
#| warning: FALSE

anes_2024 <- read_csv("../data/anes_2024_clean.csv")
codebook <- read_csv("../data/codebook.csv")

anes_2024 <- anes_2024 |>
  filter(pre_interview_mode == 2 & post_interview_mode == 2) |>
  select(-'...1', -pre_full, -post_full, -full_var_psu, 
         -full_var_stratum, -gay_marriage_view, -gay_marriage)
```

```{r}
#| label: data-cleaning

anes_2024 <- anes_2024 |>
  replace_with_na_all(condition = ~.x < 0) |>
  mutate(
    race_ethnicity = case_when(
      race_ethnicity == '-9' ~ "Refused",
      race_ethnicity == '-8' ~ "Don't know",
      race_ethnicity == '-4' ~ "Error",
      race_ethnicity == '1' ~ "White",
      race_ethnicity == '2' ~ "Black",
      race_ethnicity == '3' ~ "Hispanic",
      race_ethnicity == '4' ~ "Asian/Native Hawaiian/other Pacific Islander",
      race_ethnicity == '5' ~ "Native American/Alaska Native/other",
      race_ethnicity == '6' ~ "Multiple races",
      TRUE ~ as.character(race_ethnicity)
    ),
    gender = case_when(
      gender == '-9' ~ "Refused",
      gender == '-1' ~ "Inapplicable",
      gender == '1' ~ "Man",
      gender == '2' ~ "Woman",
      gender == '3' ~ "Nonbinary",
      gender == '4' ~ "Something else, please specify",
      TRUE ~ as.character(gender)
    ),
    educ = case_when(
      educ == '-9' ~ "Refused",
      educ == '-8' ~ "Don't Know",
      educ == '-4' ~ "Error",
      educ == '-2' ~ "Other/specify open-ended responses to be coded",
      educ == '1' ~ "Less than high school credential",
      educ == '2' ~ "High school credential",
      educ == '3' ~ "Some post-high school, no bachelor's degree",
      educ == '4' ~ "Bachelor's degree",
      educ == '5' ~ "Graduate degree",
      TRUE ~ as.character(educ)
    ),
    lib_con_7pt = case_when(
      lib_con_7pt %in% c('-9', '-4', '99') ~ NA,
      lib_con_7pt == '1' ~ "Extremely liberal",
      lib_con_7pt == '2' ~ "Liberal",
      lib_con_7pt == '3' ~ "Slightly liberal",
      lib_con_7pt == '4' ~ "Moderate; middle of the road",
      lib_con_7pt == '5' ~ "Slightly conservative",
      lib_con_7pt == '6' ~ "Conservative",
      lib_con_7pt == '7' ~ "Extremely conservative",
      TRUE ~ as.character(lib_con_7pt)
    ),
    marriage = case_when(
      marriage == '1' ~ "Married",
      marriage == '2' ~ "Married",
      marriage == '3' ~ "Widowed",
      marriage == '4' ~ "Divorced",
      marriage == '5' ~ "Separated",
      marriage == '6' ~ "Never Married",
      TRUE ~ NA
    )
  ) |>
  mutate(
    educ = factor(educ, levels = c(
      "Refused", "Don't Know", "Error", "Other/specify open-ended responses to be coded",
      "Less than high school credential", "High school credential", 
      "Some post-high school, no bachelor's degree", "Bachelor's degree", "Graduate degree"
    )),
    lib_con_7pt = factor(lib_con_7pt, levels = c(
      "Extremely liberal", "Liberal", "Slightly liberal", 
      "Moderate; middle of the road", "Slightly conservative", 
      "Conservative", "Extremely conservative", NA
    )),
    marriage = factor(marriage, levels = c(
      "Married", "Widowed", "Divorced", "Separated",
      "Never Married", NA
    ))
  )

```

# Bar chart

```{r}
#| label: top-missing-question-WEB
#| message: FALSE
#| warning: FALSE

missing_count <- anes_2024 |>
  select(-pre_interview_mode, -post_interview_mode) |>
  summarise(across(everything(), ~ sum(is.na(.x)))) |>
  pivot_longer(cols = everything(), names_to = "variable", values_to = "neg_count") |>
  arrange(desc(neg_count))

top_10_missing_count <- missing_count |>
  head(10) |>
  mutate(variable = case_when(
    variable == "poli_party_reg" ~ "Political Party Registration",
    variable == "pres_vote" ~ "2024 Presidential Vote",
    variable == "lib_con_7pt" ~ "Lib/Con 7pt Scale",
    variable == "white_thermometer" ~ "White Thermometer Rating",
    variable == "black_thermometer" ~ "Black Thermometer Rating",
    variable == "asian_thermometer" ~ "Asian Thermometer Rating",
    variable == "illegal_immigrant_thermometer" ~ "Illegal Immigrant Thermometer Rating",
    variable == "hispanic_thermometer" ~ "Hispanic Thermometer Rating",
    variable == "walz_thermometer_post" ~ "Tim Walz Thermometer Rating (Post)",
    variable == "income" ~ "Income",
    TRUE ~ as.character(variable)
  )) |>
  mutate(variable = fct_reorder(variable, neg_count))

ggplot(top_10_missing_count, aes(x = neg_count, y = variable)) +
  geom_bar(stat = "identity", fill = "#b4b5b9") +
  geom_bar(data = top_10_missing_count[1, ], stat = "identity", fill = "#7b3ad4") +
  geom_text(aes(label = neg_count, hjust = 1.15), color = "white", family = "Source Sans 3") +
  labs(title = "Top 10 Least Answered Questions (WEB)", x = "Respondents Missed", y = "Question",
       caption = "Data source: ANES 2024") +
  theme_minimal() +
  theme(text = element_text(family = "Source Sans 3"),
        plot.title = element_text(face = "bold"),
        plot.caption = element_text(face = "italic"))
```

```{r}
#| label: least-missing-question-WEB
#| message: FALSE
#| warning: FALSE

least_10_missing_count <- missing_count |>
  arrange(neg_count) |>
  head(10) |>
  mutate(variable = case_when(
    variable == "harris_thermometer_pre" ~ "Kamala Harris Thermometer Rating (Pre)",
    variable == "budget_social_security" ~ "Federal Spending on Social Security",
    variable == "voting_felons" ~ "Convicted Felons",
    variable == "international_force" ~ "Military Force on International Problems",
    variable == "biden_thermometer_pre" ~ "Joe Biden Thermometer (Pre)",
    variable == "birthright_citizenship" ~ "Birthright Citizenship",
    variable == "trump_thermometer_pre" ~ "Donald Trump Thermometer (Pre)",
    variable == "colleges_run" ~ "Running of Colleges/Universities",
    variable == "voting_id" ~ "Requirment of Voting ID",
    variable == "marriage" ~ "Marital Status",
    TRUE ~ as.character(variable)
  )) |>
  mutate(variable = fct_reorder(variable, neg_count))

ggplot(least_10_missing_count, aes(x = neg_count, y = variable)) +
  geom_bar(stat = "identity", fill = "#b4b5b9") +
  geom_bar(data = least_10_missing_count[1, ], stat = "identity", fill = "#7b3ad4") +
  geom_text(aes(label = neg_count, hjust = 1.15), color = "white", family = "Source Sans 3") +
  labs(title = "Top 10 Most Answered Questions (WEB)", x = "Respondents Missed", y = "Question",
       caption = "Data source: ANES 2024") +
  theme_minimal() +
  theme(text = element_text(family = "Source Sans 3"),
        plot.title = element_text(face = "bold"),
        plot.caption = element_text(face = "italic"))
```

```{r}
#| label: least-missing-demographic
#| message: FALSE
#| warning: FALSE

least_10_demographic_count <- missing_count |>
  arrange((neg_count)) |>
  filter(variable %in% c("age_election_day", "educ", "marriage", "income", "religion", "gender", "race_ethnicity")) |>
  head(10) |>
  mutate(variable = case_when(
    variable == "age_election_day" ~ "Age on Election Day",
    variable == "educ" ~ "Education",
    variable == "marriage" ~ "Marital Status",
    variable == "income" ~ "Income Status",
    variable == "religion" ~ "Religion",
    variable == "gender" ~ "Gender",
    variable == "race_ethnicity" ~ "Race/Ethnicity",
    TRUE ~ as.character(variable)
  )) |>
  mutate(variable = fct_reorder(variable, neg_count))

ggplot(least_10_demographic_count, aes(x = neg_count, y = variable)) +
  geom_bar(stat = "identity", fill = "#b4b5b9") +
  geom_bar(data = least_10_demographic_count[1, ], stat = "identity", fill = "#7b3ad4") +
  geom_text(aes(label = neg_count, hjust = 1.15), color = "white", family = "Source Sans 3") +
  labs(title = "Most Answered Demographic Questions (WEB)", x = "Respondents Missed", y = "Question",
       caption = "Data source: ANES 2024") +
  theme_minimal() +
  theme(text = element_text(family = "Source Sans 3"),
        plot.title = element_text(face = "bold"),
        plot.caption = element_text(face = "italic"))
```

# Missingness plot

```{r}
#| label: missingness-thermometer
#| message: FALSE
#| warning: FALSE

# demographic variables
anes_2024 |>
  select(age_election_day, educ, marriage, income, religion, gender, race_ethnicity) |>
  vis_miss(cluster = TRUE, sort_miss = TRUE)

# racial thermometer variables
anes_2024 |>
  select(white_thermometer, black_thermometer, asian_thermometer, hispanic_thermometer) |>
  vis_miss(cluster = TRUE, sort_miss = TRUE) 

# all thermometer questions
anes_2024 |>
  select(contains("thermometer")) |>
  vis_miss(cluster = TRUE, sort_miss = TRUE) +
  theme(
    axis.text.x = element_text(angle = 90)
    )
```

```{r}
#| label: missingness-issue
#| message: FALSE
#| warning: FALSE

# all issue questions
anes_2024 |>
  select(
    abortion, death_penalty, us_world_involvement, international_force, voting_id, voting_felons,
    journalists, climate_inc_temps, paid_leave, transgender_bathrooms, transgender_sports,
    birthright_citizenship, lgbt_discrimination, lgbt_adoption,
    children_immigrants, mexico_wall, ukraine_russia, israel, palestine_aid, israel_palestine,
    gaza_protests, political_violence, import_limits, immigration_levels, immigration_jobs,
    immigration_crime, immigration_citizenship, immigration_economy, immigration_customs,
    hiring_black, affirmative_action, gov_involvement, gov_regulation, income_inequality,
    equal_opportunity, gender_roles, budget_deficit, tax_millionaires, vaccines_schools,
    climate_temps, climate_regulate_emissions, gun_difficulty, gun_background_checks,
    gun_ban_assault_rifles, opioid_epidemic, police_force, free_trade, diversity,
    federal_min_wage, budget_healthcare, vaccines, sexual_harassment, transgender_military,
    china_threat, russia_threat, mexico_threat, iran_threat, japan_threat, israel_threat,
    budget_social_security, budget_public_schools, budget_border_security, budget_crime,
    budget_welfare, budget_highways, budget_aid_poor, budget_environment, colleges_run, dei
  ) |>
  vis_miss(cluster = TRUE, sort_miss = TRUE) +
  theme(
    axis.text.x = element_text(angle = 90)
    )

# social and cultural issues
anes_2024 |>
  select(
    abortion, paid_leave, transgender_bathrooms, transgender_sports, lgbt_discrimination, 
    lgbt_adoption, diversity, sexual_harassment, 
    transgender_military, colleges_run, dei
  ) |>
  vis_miss(cluster = TRUE, sort_miss = TRUE)

# guns and crime
anes_2024 |>
  select(
    death_penalty, gun_difficulty, gun_background_checks, 
    gun_ban_assault_rifles, police_force, budget_crime
  ) |>
  vis_miss(cluster = TRUE, sort_miss = TRUE)

# military and foreign policy
anes_2024 |>
  select(
    us_world_involvement, international_force, mexico_wall, ukraine_russia, israel, 
    palestine_aid, israel_palestine, gaza_protests, china_threat, russia_threat, 
    mexico_threat, iran_threat, japan_threat, israel_threat
  ) |>
  vis_miss(cluster = TRUE, sort_miss = TRUE)

# voting rights and democratic access
anes_2024 |>
  select(
    voting_id, voting_felons, journalists
  ) |>
  vis_miss(cluster = TRUE, sort_miss = TRUE)

# environment
anes_2024 |>
  select(
    climate_inc_temps, climate_temps, climate_regulate_emissions, budget_environment
  ) |>
  vis_miss(cluster = TRUE, sort_miss = TRUE)

# social welfare, healthcare, and education
anes_2024 |>
  select(
    vaccines_schools, climate_temps, opioid_epidemic, budget_healthcare, 
    vaccines, budget_social_security, budget_public_schools, budget_welfare, 
    budget_highways, budget_aid_poor
  ) |>
  vis_miss(cluster = TRUE, sort_miss = TRUE)
```

# Heat map

```{r}
#| label: missing-heatmap-educ
#| message: FALSE
#| warning: FALSE

anes_2024 |>
  select(educ, 
         "White Thermometer Rating" = white_thermometer, 
         "Black Thermometer Rating" = black_thermometer, 
         "Asian Thermometer Rating" = asian_thermometer, 
         "Hispanic Thermometer Rating" = hispanic_thermometer) |>
  gg_miss_fct(fct = educ) +
  scale_fill_gradient(low = "white", high = "#7b3ad4") +
  theme_minimal() +
  labs(title = "Missing Data Patterns by Education Level \nand Race Thermometer Questions (WEB)",
       x = "Education",
       y = "Question",
       fill = "Missing %") +
  theme(
    text = element_text(family = "Source Sans 3"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(face = "italic"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    )

anes_2024 |>
  select(educ, colleges_run, budget_public_schools, vaccines_schools, children_immigrants, affirmative_action) |>
  gg_miss_fct(fct = educ) +
  scale_fill_gradient(low = "white", high = "#7b3ad4") +
  theme_minimal() +
  labs(title = "Missing Data Patterns by Education Level \nand School Questions (WEB)",
       x = "Education",
       y = "Question",
       fill = "Missing %") +
  theme(
    text = element_text(family = "Source Sans 3"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(face = "italic"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    )



```

```{r}
#| label: missing-heatmap-race
#| message: FALSE
#| warning: FALSE

anes_2024 |>
  select(race_ethnicity, 
         "White Thermometer Rating" = white_thermometer, 
         "Black Thermometer Rating" = black_thermometer, 
         "Asian Thermometer Rating" = asian_thermometer, 
         "Hispanic Thermometer Rating" = hispanic_thermometer) |>
  mutate(race_ethnicity = fct_relevel(
    race_ethnicity, 
    "White", 
    "Hispanic", 
    "Black", 
    "Asian/Native Hawaiian/other Pacific Islander",
    "Native American/Alaska Native/other")) |>
  gg_miss_fct(fct = race_ethnicity) +
  scale_fill_gradient(low = "white", high = "#7b3ad4") +
  theme_minimal() +
  labs(title = "Missing Data Patterns by Race \nand Race Thermometer Questions (WEB)",
       x = "Race",
       y = "Question",
       fill = "Missing %") +
  theme(
    text = element_text(family = "Source Sans 3"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(face = "italic"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    )
```

```{r}
#| label: missing-heatmap-libcon
#| message: FALSE
#| warning: FALSE

anes_2024 |>
  select(lib_con_7pt, 
         "White Thermometer Rating" = white_thermometer, 
         "Black Thermometer Rating" = black_thermometer, 
         "Asian Thermometer Rating" = asian_thermometer, 
         "Hispanic Thermometer Rating" = hispanic_thermometer) |>
  gg_miss_fct(fct = lib_con_7pt) +
  scale_fill_gradient(low = "white", high = "#7b3ad4") +
  theme_minimal() +
  labs(title = "Missing Data Patterns by Ideology \nand Race Thermometer Questions (WEB)",
       x = "Ideology",
       y = "Question",
       fill = "Missing %") +
  theme(
    text = element_text(family = "Source Sans 3"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(face = "italic"),
    axis.text.x = element_text(angle = 45, hjust = 1)
    )

anes_2024 |>
  select(lib_con_7pt, poli_party_reg, pres_vote, black_thermometer, white_thermometer) |>
  gg_miss_fct(fct = lib_con_7pt) +
  scale_fill_gradient(low = "white", high = "#7b3ad4") +
  theme_minimal() +
  labs(title = "Missing Data Patterns by Ideology \nand Top 5 Unanswered Questions (WEB)",
       x = "Ideology",
       y = "Question",
       fill = "Missing %") +
  theme(
    text = element_text(family = "Source Sans 3"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(face = "italic"),
    axis.text.x = element_text(angle = 45, hjust = 1)
    )

anes_2024 |>
  select(lib_con_7pt, liberals_thermometer, conservatives_thermometer) |>
  gg_miss_fct(fct = lib_con_7pt) +
  scale_fill_gradient(low = "white", high = "#7b3ad4") +
  theme_minimal() +
  labs(title = "Missing Data Patterns by Ideology \nand Ideological Questions (WEB)",
       x = "Ideology",
       y = "Question",
       fill = "Missing %") +
  theme(
    text = element_text(family = "Source Sans 3"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(face = "italic"),
    axis.text.x = element_text(angle = 45, hjust = 1)
    )

anes_2024 |>
  gg_miss_fct(fct = lib_con_7pt) +
  scale_fill_gradient(low = "white", high = "#7b3ad4") +
  theme_minimal() +
  labs(title = "Missing Data Patterns by Ideology \nand All Survey Questions (WEB)",
       x = "Ideology",
       y = "Question",
       fill = "Missing %") +
  theme(
    text = element_text(family = "Source Sans 3"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(face = "italic"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_blank()
    )

```

```{r}
#| label: missing-heatmap-marriage
#| message: FALSE
#| warning: FALSE

anes_2024 |>
  select(marriage, white_thermometer, black_thermometer, asian_thermometer, hispanic_thermometer) |>
  gg_miss_fct(fct = marriage) +
  scale_fill_gradient(low = "white", high = "#7b3ad4") +
  theme_minimal() +
  labs(title = "Missing Data Patterns by Marriage \nand Race Thermometer Questions (WEB)",
       x = "Marital Status",
       y = "Question",
       fill = "Missing %") +
  theme(
    text = element_text(family = "Source Sans 3"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(face = "italic"),
    axis.text.x = element_text(angle = 45, hjust = 1)
    )

anes_2024 |>
  select(marriage, poli_party_reg, pres_vote, black_thermometer, white_thermometer) |>
  gg_miss_fct(fct = marriage) +
  scale_fill_gradient(low = "white", high = "#7b3ad4") +
  theme_minimal() +
  labs(title = "Missing Data Patterns by Marriage \nand Top 5 Unanswered Questions (WEB)",
       x = "Marital Status",
       y = "Question",
       fill = "Missing %") +
  theme(
    text = element_text(family = "Source Sans 3"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(face = "italic"),
    axis.text.x = element_text(angle = 45, hjust = 1)
    )

anes_2024 |>
  gg_miss_fct(fct = marriage) +
  scale_fill_gradient(low = "white", high = "#7b3ad4") +
  theme_minimal() +
  labs(title = "Missing Data Patterns by Marriage \nand All Survey Questions (WEB)",
       x = "Marital Status",
       y = "Question",
       fill = "Missing %") +
  theme(
    text = element_text(family = "Source Sans 3"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(face = "italic"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_blank()
    )

```
```{r}
#| label: missing-heatmap-gender
#| message: FALSE
#| warning: FALSE

anes_2024 |>
  select(gender, white_thermometer, black_thermometer, asian_thermometer, hispanic_thermometer) |>
  gg_miss_fct(fct = gender) +
  scale_fill_gradient(low = "white", high = "#7b3ad4") +
  theme_minimal() +
  labs(title = "Missing Data Patterns by Gender \nand Race Thermometer Questions (WEB)",
       x = "Marital Status",
       y = "Question",
       fill = "Missing 
%") +
  theme(
    text = element_text(family = "Source Sans 3"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(face = "italic"),
    axis.text.x = element_text(angle = 45, hjust = 1)
    )

anes_2024 |>
  select(gender, 
         "Feminists Thermometer Rating" = feminists_thermometer, 
         "Gay and Lesbian Thermometer Rating" = lgbt_thermometer, 
         "Transgender Thermometer Rating" = transgender_thermometer, 
         "Transgender Bathrooms" = transgender_bathrooms, 
         "Transgender Sports" = transgender_sports, 
         "Gender Roles" = gender_roles, 
         "Transgender Military" = transgender_military) |>
  gg_miss_fct(fct = gender) +
  scale_fill_gradient(low = "white", high = "#7b3ad4") +
  theme_minimal() +
  labs(title = "Missing Data Patterns by Gender \nand Gender Questions (WEB)",
       x = "Marital Status",
       y = "Question",
       fill = "Missing %") +
  theme(
    text = element_text(family = "Source Sans 3"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(face = "italic"),
    axis.text.x = element_text(angle = 45, hjust = 1)
    )

anes_2024 |>
  gg_miss_fct(fct = gender) +
  scale_fill_gradient(low = "white", high = "#7b3ad4") +
  theme_minimal() +
  labs(title = "Missing Data Patterns by Gender \nand All Survey Questions (WEB)",
       x = "Marital Status",
       y = "Question",
       fill = "Missing %") +
  theme(
    text = element_text(family = "Source Sans 3"),
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(face = "italic"),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_blank()
    )

```
